# Generated by Django 4.2 on 2023-04-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_review_created_alter_review_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-updated',)},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
